const adminsLabel = [
    "ID",
    "Image",
    "Name",
    "Organization",
    "Email",
    "Contact No.",
    "Action",
  ],
  employeesLabel = [
    "ID",
    "Image",
    "Name",
    "Department",
    "Email",
    "Contact No.",
    "Action",
  ],
  organizationLabel = [
    "ID",
    "Image",
    "Name",
    "Location",
    "Email",
    "Contact No.",
    "Action",
  ],
  complaintLabel = [
    "ID",
    "Admin Name",
    "Organization",
    "Description",
    "Submission Date",
    "Status.",
    "Action",
  ],
  InventoryLabel = [
    "ID",
    "Item Name",
    "Description",
    "Category",
    "Sub-Category",
    "Price(Rs)",
    "Action",
  ],
  categoryLabel = [
    "ID",
    "Category Name",
    "Number of Sub-Categories",
    "Number of Vendors",
    "Action",
  ],
  departmentLabel = ["ID", "Name", "Email", "Contact No.", "Action"],
  subCategoryLabel = [
    "Sub-Category Name",
    "Vendor Name",
    "Quantity",
    "Quantity Assigned",
    "Quantity Unassigned",
    "Quantity Faulty",
    "Action",
  ],
  requestsLabel=[
    "ID",
    "Employee Name",
    "Item Name",
    "Category",
    "Sub Category",
    "Date",
    "Status",
    "Action"
  ],
  ownRequestLabel = [
    "ID",
    "Item Name",
    "Category",
    "Sub Category",
    "Type",
    "Date",
    "Status",
    "Action"
  ],
  returnsLabel=[
    "ID",
    "Employee Name",
    "Item Name",
    "Category",
    "Sub Category",
    "Type",
    "Date",
    "Status",
    "Action"
  ],
  vendorsLabel = [
    "ID",
    "Vendor Name",
    "Contact Number",
    "Category",
    "Sub Category",
    "Action"
  ],
  adminEmpComplaintLabel = [
    "ID",
    "Employee Name",
    "Department",
    "Description",
    "Submission Date",
    "Status",
    "Action"
  ],
  ownComplaintLabel =[
    "ID",
    "Title",
    "Description",
    "Submission Date",
    "Status",
    "Action"
  ],
  ownInventoryLabel = [
    "ID",
    "Item Name",
    "Category",
    "Sub-Category",
    "Assigned Date",
    "Assigned By"
  ],
  data = [
    createData("Cupcake", 305, 3.7, 67, 4.3, 14),
    createData("Donut", 452, 25.0, 51, 4.9, 14),
    createData("Eclair", 262, 16.0, 24, 6.0, 14),
    createData("Frozen yoghurt", 159, 6.0, 24, 4.0, 14),
    createData("Gingerbread", 356, 16.0, 49, 3.9, 14),
    createData("Honeycomb", 408, 3.2, 87, 6.5, 14),
    createData("Ice cream sandwich", 237, 9.0, 37, 4.3, 14),
    createData("Jelly Bean", 375, 0.0, 94, 0.0, 14),
    createData("KitKat", 518, 26.0, 65, 7.0, 14),
    createData("Lollipop", 392, 0.2, 98, 0.0, 14),
    createData("Marshmallow", 318, 0, 81, 2.0, 14),
    createData("Nougat", 360, 19.0, 9, 37.0, 14),
    createData("Oreo", 437, 18.0, 63, 4.0, 14),
  ],
  categoryData = [
    {
      id: "Cupcake",
      calories: 305,
      fat: 3.7,
      carbs: 67,
      subCategories: [
        {
          id: 1,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 2,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
    {
      id: "Donut",
      calories: 452,
      fat: 25,
      carbs: 51,
      subCategories: [
        {
          id: 3,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 4,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
    {
      id: "Eclair",
      calories: 262,
      fat: 16,
      carbs: 24,
      subCategories: [
        {
          id: 5,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 6,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
    {
      id: "Frozen yoghurt",
      calories: 159,
      fat: 6,
      carbs: 24,
      subCategories: [
        {
          id: 7,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 8,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
    {
      id: "Gingerbread",
      calories: 356,
      fat: 16,
      carbs: 49,
      subCategories: [
        {
          id: 9,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 10,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
    {
      id: "Honeycomb",
      calories: 408,
      fat: 3.2,
      carbs: 87,
      subCategories: [
        {
          id: 11,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 12,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
    {
      id: "Ice cream sandwich",
      calories: 237,
      fat: 9,
      carbs: 37,
      subCategories: [
        {
          id: 13,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 14,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
    {
      id: "Jelly Bean",
      calories: 375,
      fat: 0,
      carbs: 94,
      subCategories: [
        {
          id: 15,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 16,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
    {
      id: "KitKat",
      calories: 518,
      fat: 26,
      carbs: 65,
      subCategories: [
        {
          id: 17,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 18,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
    {
      id: "Lollipop",
      calories: 392,
      fat: 0.2,
      carbs: 98,
      subCategories: [
        {
          id: 19,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
        {
          id: 20,
          name: "Laptop",
          vendorName: "Vendor Name",
          quantity: 30,
          quantityAssigned: 25,
          quantityUnassigned: 4,
          quantityFaulty: 1,
        },
      ],
    },
  ],
  organizations = [
    { id: 1, name: "Gigalabs" },
    { id: 2, name: "Fast Tech" },
    { id: 3, name: "Nextbridge" },
  ],
  departments = [
    {
      id: 1,
      name: "Buisness Development",
      email: "bd@gmail.com",
      contactNo: "+92324092348",
    },
    {
      id: 2,
      name: "Development",
      email: "bd@gmail.com",
      contactNo: "+92324092348",
    },
    {
      id: 3,
      name: "Human Resource",
      email: "bd@gmail.com",
      contactNo: "+92324092348",
    },
  ],
  userDetails = {
    "Name": "John Doe",
    "Contact No.": "+921298312893",
    Email: "someone@gmail.co",
    Department: "304 Johar Town",
  },
  complaintDetails = {
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  requestDetails = {
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    Item: "Mac Book pro 2015",  
    Category: "Electronics",
    SubCategory: "Laptop"
    },
  itemDetails = {
    "Item Name": "Mac Book 2013",
    "Serial No": "4398768",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    Category: "Electronics",
    "Sub-Category": "Mouse",
    "Date Of Purchase": "11/12/2011",
    "Unit Price": "Rs 150,000",
    "Current Price": "Rs 200,000",
    "Depriciated Price": "Rs 50,000",
    "Percentage Depriciation": "30%",
  },
  subCategoryDetails = {
    "Category Name": "Electronics",
    "Sub-Category Name": "Laptop",
    "Total Quantity": 10,
    "Quantity Assigned": 5,
    "Quantity Unassigned": 4,
    "Quantity Faulty": 1,
  },
  categoryDetail = {name: "Electronics", subCategories : [
    {name: "Laptop"},
    {name: "Mouse"},
    {name: "Mobile"},
    {name: "Headphones"},
    {name: "Printer"}
  ]}, 
  vendorDetails = {
    Name: "John Doe",
    "Contact Number": "+9233434784",
    "Category": "Electronics",
    "Sub Categories": [{name: "laptop"}, {name: "Mobile"}]
  },
  vendors = [
    { Name: "Corey Botosh", "Contact Number": "+923453453" },
    { Name: "Corey Botosh", "Contact Number": "+923453453" },
  ],
  complaintAttachements = ["/dummy2.png", "/dummy2.png", "/dummy2.png"],
  dummySelect = [
    { name: "dummy1" },
    { name: "dummy2" },
    { name: "dummy3" },
    { name: "dummy4" },
  ],
  complaintStatusOptions = [{ status: "Pending" }, { status: "Resolved" }],
  returnTypeOptions = [{ type: "Repair" }, { type: "Replace" }],
  returnStatusOptions = [{status: "Pending"},{status: "Approved"}],
  requestStatusOptions = [{status: "Pending"},{status: "Rejected"},{status: "Approved"}],
  multiSelectOptions = [
    { label: "subCategory", value: "1" },
    { label: "subCategory", value: "2" },
    { label: "subCategory", value: "3" },
  ],
  employeeProfile = {
    "Full Name": "John Doe",
    "Designation": "Jr. Software Engineer",
    "Contact Number": "+9234767434",
    "Company Experience": "2 years",
    "Email Address": "user@gmail.com",
    "Department": "Development",
    "Education": "Bachelors in Computer Science",
    "Total Experience": "6 years"
  }

function createData(id, calories, fat, carbs, protein, hb) {
  return { id, calories, fat, carbs, protein, hb };
}

export {
  categoryData,
  categoryDetail,
  departmentLabel,
  itemDetails,
  subCategoryLabel,
  vendors,
  subCategoryDetails,
  InventoryLabel,
  categoryLabel,
  data,
  userDetails,
  complaintDetails,
  requestDetails,
  complaintAttachements,
  organizations,
  departments,
  organizationLabel,
  adminsLabel,
  complaintLabel,
  requestsLabel,
  returnsLabel,
  dummySelect,
  complaintStatusOptions,
  returnTypeOptions,
  returnStatusOptions,
  requestStatusOptions,
  multiSelectOptions,
  vendorsLabel,
  vendorDetails,
  adminEmpComplaintLabel,
  ownComplaintLabel,
  ownRequestLabel,
  employeeProfile,
  ownInventoryLabel,
  employeesLabel
};
