//Users
export const LOG_IN = 'Log In'
export const CREATE_USER = 'Create USER'
export const USER_ERROR = 'Error while creating a user'
export const SET_USER = 'Set User'
export const SET_CREATED_USER = 'Set create user'
export const GET_USERS = 'Get all users'
export const SET_USERS = 'Set all users'
export const SET_USER_DETAILS = 'Set user details'
export const GET_USER_DETAILS = 'Get user details'
export const EDIT_USER = 'Edit user'
export const DELETE_USER = 'Delete user'
export const SET_ERROR = 'Set Error' //login error
export const LOG_OUT = 'Log Out'
export const SEARCH_USERS = "Search users"
export const SELECT_USER_ORGANIZATION = "Select user using their organization"
export const SET_SEARCHED_USERS = "Setting searched users"
export const SET_USERS_COUNT = "Setting users count"
export const GET_USERS_COUNT = "Getting users count"
//Complaints
export const SET_COMPLAINTS_COUNT = "Setting complaints count"
export const GET_COMPLAINTS_COUNT = "Getting complaints count"
export const SEARCH_COMPLAINTS = "Search complaints"
export const SELECT_COMPLAINTS_ORGANIZATION = "Set complaints by organization"
export const SELECT_COMPLAINTS_STATUS = "Set complaints by status"
export const SET_SEARCHED_COMPLAINTS = "Set searched complaints"
export const CREATE_COMPLAINT = "Create a complaint" 
export const GET_COMPLAINTS = "Get all complaints"
export const GET_COMPLAINTS_DETAILS = "Get a complaint"
export const DELETE_COMPLAINT = "Delete a complaint"
export const EDIT_COMPLAINT = "Edit a complaint"
export const SET_COMPLAINTS = "Set all complanits"
export const SET_OWN_COMPLAINTS = "Set own complanits" 
export const SET_CREATED_COMPLAINTS = "Set a created complaint"
export const SET_COMPLAINT_DETAILS = "Set complaint details"
export const SET_COMPLAINT_ERROR = "Set any complaint regarding error"
//Organizations
export const SET_ORGANIZATIONS_COUNT = "Setting organization count"
export const GET_ORGANIZATIONS_COUNT = "Getting organization count"
export const CREATE_ORGANIZATION = 'Create organization'
export const SET_CREATE_ORGANIZATION_ERROR = 'Create organization error'
export const SET_CREATED_ORGANIZATION = "Set a created organization"
export const GET_ORGANIZATIONS = 'Get All Organizations'
export const SET_ALL_ORGANIZATIONS = 'Set All Organizations'
export const GET_ORGANIZATION_DETAIL = 'Get Organization Details'
export const SET_ORGANIZATION_DETAIL = 'Set Organization Details'
export const EDIT_ORGANIZATION = 'Edit Organization'
export const EDIT_ORGANIZATION_DETAIL = 'Edit details'
export const ORGANIZATIONS_SEARCH = 'Search organizations'
export const SET_ORGANIZATION_SEARCH = 'Setting organizations based on search'
export const SELECT_USING_LOCATION = 'Select organization using location'
export const DELETE_ORGANIZATION = 'Delete an organization'
//Items
export const SET_ITEMS_COUNT = "Setting item count"
export const GET_ITEMS_COUNT = "Getting item count"
export const CREATE_ITEM = 'Create item'
export const SET_CREATE_ITEM_ERROR = 'Create item error'
export const SET_CREATED_ITEM = "Set a created item"
export const GET_ITEMS = 'Get All items'
export const SET_ALL_ITEMS = 'Set All items'
export const GET_ITEM_DETAIL = 'Get item Details'
export const SET_ITEM_DETAIL = 'Set item Details'
export const EDIT_ITEM = 'Edit item'
export const ITEMS_SEARCH = 'Search items'
export const SET_ITEM_SEARCH = 'Setting items based on search'
export const SELECT_ITEM_USING_CATEGORY = 'Select item using category'
export const SELECT_ITEM_USING_SUBCATEGORY = 'Select item using subcategory'
export const DELETE_ITEM = 'Delete an item'
//Vendors
export const SET_VENDORS_COUNT = "Setting VENDOR count"
export const GET_VENDORS_COUNT = "Getting VENDOR count"
export const CREATE_VENDOR = 'Create VENDOR'
export const SET_CREATE_VENDOR_ERROR = 'Create VENDOR error'
export const SET_CREATED_VENDOR = "Set a created VENDOR"
export const GET_VENDORS = 'Get All VENDORS'
export const SET_ALL_VENDORS = 'Set All VENDORS'
export const GET_VENDOR_DETAIL = 'Get VENDOR Details'
export const SET_VENDOR_DETAIL = 'Set VENDOR Details'
export const EDIT_VENDOR = 'Edit VENDOR'
export const VENDORS_SEARCH = 'Search VENDORS'
export const SELECT_VENDORY_BY_CATEGORY = 'Select VENDOR using category'
export const SELECT_VENDORY_BY_SUBCATEGORY = 'Select VENDOR using subcategory'
export const DELETE_VENDOR = 'Delete an VENDOR'
//Category
export const SET_CATEGORY_COUNT = "Setting CATEGORY count"
export const GET_CATEGORY_COUNT = "Getting CATEGORY count"
export const CREATE_CATEGORY = 'Create CATEGORY'
export const SET_CREATE_CATEGORY_ERROR = 'Create CATEGORY error'
export const SET_CREATED_CATEGORY = "Set a created CATEGORY"
export const GET_CATEGORY = 'Get All CATEGORY'
export const SET_ALL_CATEGORY = 'Set All CATEGORY'
export const GET_CATEGORY_DETAIL = 'Get CATEGORY Details'
export const SET_CATEGORY_DETAIL = 'Set CATEGORY Details'
export const EDIT_CATEGORY = 'Edit CATEGORY'
export const CATEGORY_SEARCH = 'Search CATEGORY'
export const SET_CATEGORY_SEARCH = 'Setting CATEGORY based on search'
export const SELECT_CATEGORY_BY_ORGANIZATION = 'Select CATEGORY using organization'
export const DELETE_CATEGORY = 'Delete an CATEGORY'
//Departments
export const CREATE_DEPARTMENT = 'Create DEPARTMENT'
export const SET_CREATE_DEPARTMENT_ERROR = 'Create DEPARTMENT error'
export const SET_CREATED_DEPARTMENT = "Set a created DEPARTMENT"
export const GET_DEPARTMENT = 'Get All DEPARTMENT'
export const SET_ALL_DEPARTMENT = 'Set All DEPARTMENT'
export const GET_DEPARTMENT_DETAIL = 'Get DEPARTMENT Details'
export const SET_DEPARTMENT_DETAIL = 'Set DEPARTMENT Details'
export const EDIT_DEPARTMENT = 'Edit DEPARTMENT'
export const DEPARTMENT_SEARCH = 'Search DEPARTMENT'
export const SET_DEPARTMENT_SEARCH = 'Setting DEPARTMENT based on search'
export const DELETE_DEPARTMENT = 'Delete an DEPARTMENT'
//Requests
export const CREATE_REQUEST = 'Create REQUEST'
export const SET_CREATE_REQUEST_ERROR = 'Create REQUEST error'
export const SET_CREATED_REQUEST = "Set a created REQUEST"
export const GET_REQUESTS = 'Get All REQUESTS'
export const SET_ALL_REQUESTS = 'Set All REQUESTS'
export const GET_REQUEST_DETAIL = 'Get REQUEST Details'
export const SET_REQUEST_DETAIL = 'Set REQUEST Details'
export const EDIT_REQUEST = 'Edit REQUEST'
export const SET_REQUEST_SEARCH = 'Setting REQUEST based on search'
export const DELETE_REQUEST = 'Delete an REQUEST'
export const SELECT_REQUEST_BY_STATUS = 'Select REQUEST using status'
export const SELECT_REQUEST_BY_TYPE = 'Select REQUEST using type'
export const REQUEST_SEARCH = 'Search REQUEST'