const adminsLabel = [
    "ID",
    "Image",
    "Name",
    "Organization",
    "Email",
    "Contact No.",
    "Action",
  ],
  employeesLabel = [
    "ID",
    "Image",
    "Name",
    "Department",
    "Email",
    "Contact No.",
    "Action",
  ],
  organizationLabel = [
    "ID",
    "Image",
    "Name",
    "Location",
    "Email",
    "Contact No.",
    "Action",
  ],
  complaintLabel = [
    "ID",
    "Admin Name",
    "Organization",
    "Description",
    "Submission Date",
    "Status.",
    "Action",
  ],
  InventoryLabel = [
    "ID",
    "Item Name",
    "Description",
    "Category",
    "Sub-Category",
    "Price(Rs)",
    "Action",
  ],
  categoryLabel = [
    "ID",
    "Category Name",
    "Number of Sub-Categories",
    "Number of Vendors",
    "Action",
  ],
  departmentLabel = ["ID", "Name", "Email", "Contact No.", "Action"],
  subCategoryLabel = [
    "Sub-Category Name",
    "Vendor Name",
    "Quantity",
    "Quantity Assigned",
    "Quantity Unassigned",
    "Quantity Faulty",
    "Action",
  ],
  requestsLabel=[
    "ID",
    "Employee Name",
    "Item Name",
    "Category",
    "Sub Category",
    "Date",
    "Status",
    "Action"
  ],
  ownRequestLabel = [
    "ID",
    "Item Name",
    "Category",
    "Sub Category",
    "Type",
    "Date",
    "Status",
    "Action"
  ],
  returnsLabel=[
    "ID",
    "Employee Name",
    "Item Name",
    "Category",
    "Sub Category",
    "Type",
    "Date",
    "Status",
    "Action"
  ],
  vendorsLabel = [
    "ID",
    "Vendor Name",
    "Contact Number",
    "Category",
    "Sub Category",
    "Action"
  ],
  adminEmpComplaintLabel = [
    "ID",
    "Employee Name",
    "Department",
    "Description",
    "Submission Date",
    "Status",
    "Action"
  ],
  ownComplaintLabel =[
    "ID",
    "Title",
    "Description",
    "Submission Date",
    "Status",
    "Action"
  ],
  ownInventoryLabel = [
    "ID",
    "Item Name",
    "Category",
    "Sub-Category",
    "Assigned Date",
    "Assigned By"
  ],

  complaintStatusOptions = [{ status: "Pending" }, { status: "Resolved" }],
  returnTypeOptions = [{ type: "Repair" }, { type: "Replace" }],
  returnStatusOptions = [{status: "Pending"},{status: "Approved"}],
  requestStatusOptions = [{status: "Pending"},{status: "Rejected"},{status: "Approved"}],
  requestTypeOptions = [{type: "Acquire"}, {type: "Faulty"}],
  multiSelectOptions = [
    { label: "subCategory", value: "1" },
    { label: "subCategory", value: "2" },
    { label: "subCategory", value: "3" },
  ]


export {
  departmentLabel,
  subCategoryLabel,
  InventoryLabel,
  categoryLabel,
  organizationLabel,
  adminsLabel,
  complaintLabel,
  requestsLabel,
  returnsLabel,
  complaintStatusOptions,
  returnTypeOptions,
  returnStatusOptions,
  requestStatusOptions,
  requestTypeOptions,
  multiSelectOptions,
  vendorsLabel,
  adminEmpComplaintLabel,
  ownComplaintLabel,
  ownRequestLabel,
  ownInventoryLabel,
  employeesLabel
};
